# Generated by Django 6.0.6 on 2026-06-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image_name', models.CharField(max_length=100)),
            ],
        ),
    ]
